# Generated by Django 5.2.4 on 2025-07-30 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_alter_review_options_review_helpful_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='postal_code',
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='description',
            field=models.TextField(blank=True, verbose_name='説明'),
        ),
    ]

