# Generated by Django 5.2.4 on 2025-07-29 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeWebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_event_id', models.CharField(max_length=255, unique=True, verbose_name='StripeイベントID')),
                ('event_type', models.CharField(max_length=100, verbose_name='イベントタイプ')),
                ('processed', models.BooleanField(default=False, verbose_name='処理済み')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='エラーメッセージ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
            ],
            options={
                'verbose_name': 'WebHookログ',
                'verbose_name_plural': 'WebHookログ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Stripe顧客ID'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='StripeサブスクリプションID'),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_subscription_id', models.CharField(max_length=255, unique=True, verbose_name='StripeサブスクリプションID')),
                ('stripe_customer_id', models.CharField(max_length=255, verbose_name='Stripe顧客ID')),
                ('stripe_price_id', models.CharField(max_length=255, verbose_name='Stripe価格ID')),
                ('status', models.CharField(choices=[('active', 'アクティブ'), ('canceled', 'キャンセル済み'), ('past_due', '支払い遅延'), ('unpaid', '未払い'), ('trialing', 'トライアル中')], max_length=20, verbose_name='ステータス')),
                ('current_period_start', models.DateTimeField(verbose_name='現在の期間開始日')),
                ('current_period_end', models.DateTimeField(verbose_name='現在の期間終了日')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'サブスクリプション',
                'verbose_name_plural': 'サブスクリプション',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_payment_intent_id', models.CharField(max_length=255, unique=True, verbose_name='Stripe決済ID')),
                ('stripe_invoice_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Stripe請求書ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='金額')),
                ('currency', models.CharField(default='jpy', max_length=3, verbose_name='通貨')),
                ('status', models.CharField(choices=[('succeeded', '成功'), ('pending', '処理中'), ('failed', '失敗'), ('canceled', 'キャンセル'), ('refunded', '返金済み')], max_length=20, verbose_name='ステータス')),
                ('description', models.TextField(blank=True, null=True, verbose_name='説明')),
                ('failure_reason', models.TextField(blank=True, null=True, verbose_name='失敗理由')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='支払い日時')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.subscription', verbose_name='サブスクリプション')),
            ],
            options={
                'verbose_name': '決済履歴',
                'verbose_name_plural': '決済履歴',
                'ordering': ['-created_at'],
            },
        ),
    ]

